name: homestyle
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:



  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  animated_text: ^1.0.2
  graphql_flutter: ^3.1.0
  shared_preferences: ^0.5.12+4








dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
    - images/
    - images/cat/

  fonts:
    - family: Orbitron-Black
      fonts:
        - asset: fonts/Orbitron-Black.ttf

    - family: NothingYouCouldDo-Regular
      fonts:
          - asset: fonts/NothingYouCouldDo-Regular.ttf

    - family: Scheherazade-Regular
      fonts:
          - asset: fonts/Scheherazade-Regular.ttf


module:
  androidX: true # Add this line.
